require "keymaps"
require "options"
require "lazy-config"

require "alpha-config"
require "autopairs"
require "bufferline-config"
require "comments-config"
require "colortheme"
require "neovim-tasks-config"
require "nvim-tree-config"
require "git-signs"
require "hop-config"
require "indentline-config"
require "lsp-config"
require "lualine-config"
require "luasnip-config"
require "telescope-config"
require "toggleterm-config"
require "treesitter-config"

require "whichkey"
